#!/bin/bash

# GOAL
#   Use this to decrypt the credentials file

# Encrypted File with the credentials
CRED_FILE_ENCRYPTED=~/credentials.asc

# File with the pass-phrase
GPG_PASS_FILE=~/.private/gpg_pass_file.txt

# Target of the decryption
CRED_FILE=~/.aws/credentials.mfa

if [ ! -f $CRED_FILE_ENCRYPTED ]; then
    echo "Encrypted file does not exist: $CRED_FILE_ENCRYPTED"
    exit 1
fi


if [ ! -f $GPG_PASS_FILE ]; then
    echo "Pass-phrase file does not exist: $GPG_PASS_FILE"
    exit 1
fi


# Helper for getting data from ~/credentials.asc
cat $GPG_PASS_FILE | gpg  --batch --yes --passphrase-fd 0 -d $CRED_FILE_ENCRYPTED > $CRED_FILE

echo "Credential file was created here"
ls -l $CRED_FILE
